<?php
namespace App\Controllers\administrator;
/**
* Auto Generated By TrigerIgniter v1
* Codeigniter Version 4.1.x
* Codeigniter Controller
**/

use App\Models\Master_model;
use App\Controllers\BaseController;
use App\Models\Deliver_model;
use App\Models\Pickup_model;

class Master extends BaseController
{
    protected $model; //Default Models Of this Controler

    /**
     * Class constructor.
     */ 
    public function __construct()
    {
        $this->model = new Master_model(); //Set Default Models Of this Controller
        $this->Template = $this->defaultTemplate(); //Template Of this Page
        $this->pager = \Config\Services::pager(); // Pagination
        $this->validation =  \Config\Services::validation();
    }

    // This event executed after constructor
    protected function onLoad(){
        $this->PageData->parent = "administrator/Master";
        $this->PageData->header = (session()->has("level") ? NULL : ucfirst(str_replace("_", '', session("level"))) . " :: ") . 'Master';
        $this->PageData->access = ["administrator"];
        // check access level
        if (! $this->access_allowed()) {
            session()->setFlashdata("ci_login_flash_message", 'Login session outdate. Please re-Login !');
            session()->setFlashdata("ci_login_flash_message_type", "text-danger");
            throw new \CodeIgniter\Router\Exceptions\RedirectException();
        };
    
    }

    //TEMPLATE OF THIS PAGE
    private function defaultTemplate()
    {
        return (object) [
            'container' => 'administrator/_templates/Container',
            'header' => 'administrator/_templates/header',
            'navbar' => 'administrator/_templates/navbar',
            'sidebar' => 'administrator/_templates/sidebar',
            'footer' => 'administrator/_templates/footer',
        ];
    }
    
    private function access_allowed(){
        $allowed = FALSE;
        if (count($this->PageData->access)==0) return TRUE;
        if (! session()->has("level"))  return FALSE;
        foreach ($this->PageData->access as $key => $value) {
            if(session("level")==$value){
                $allowed=TRUE;
                break;
            }
        };
        return $allowed;
    }

    //INDEX
    public function index($status = 1)
    {
        //indexstart
        $c = $this->model->select("COUNT(resi) AS c")->join("pickup", "master.id_pickup=pickup.id", "LEFT")->where("master.status", 0)->where("pickup.status = 1", NULL, FALSE)->first()->c;
        session()->set("verivikasi", $c);
        
        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL){
            if (session()->has("sorting_table")) {
                if (session("sorting_table")==$this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        }else{
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            $sortorder = strtoupper($sortorder);
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if (in_array($sortcolumn, $this->model->getFields())){
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
                session()->set('sortcolumn', $sortcolumn);
                session()->set('sortorder', $sortorder);
                session()->set('sorting_table', $this->model->table);
            }else{
                $sortcolumn = NULL;
                $sortorder = NULL;
                session()->remove('sortcolumn');
                session()->remove('sortorder');
                session()->remove('sorting_table');
            }
        }

        // How many data shows each page
        $perPage = $this->request->getPostGet("perPage");
        if ($perPage == NULL) {
            if (session()->has("paging_table")) {
                if (session("paging_table")==$this->model->table) {
                    $perPage = session("perPage");
                };
            };
        };
        if ($perPage != NULL) {
            // Minimum data per-page = 2
            if ($perPage <= 0) $perPage = 2;
            session()->set('perPage', $perPage);
            session()->set('paging_table', $this->model->table);
        }else{
            // Default data per-page = 20
            $perPage = 20;
            session()->remove('paging_table');
            session()->remove('perPage');
        }

        $page = $this->request->getGet("page");
        $page = $page<=0?1:$page;
        $keyword = $this->request->getGetPost("keyword");
        $s = "master.status = 0";
        if ($status == 1) {
            $s = "master.status = 1 AND pickup.status = 1";
            $this->PageData->title = "Pickup Selesai";
            $this->PageData->subtitle = [
                $this->PageData->title => 'administrator/Master/index'
            ];
            $this->PageData->url = "administrator/Master/index";
        }else {
            $s = "master.status = 0 AND pickup.status = 1";
            $this->PageData->title = "Verivikasi Pickup";
            $this->PageData->subtitle = [
                $this->PageData->title => 'administrator/Master/verivikasi'
            ];
            $this->PageData->url = "administrator/Master/verivikasi";
        }
        $this->model->where($s, NULL, FALSE);
        $totalrecord = $this->model->getData($keyword)->countAllResults();        
        $this->model->where($s, NULL, FALSE);
        $data = [
            'sortcolumn' => $sortcolumn,
            'sortorder' => $sortorder,
            'data' => $this->model->getData($keyword)->paginate($perPage),
            'perPage' => $perPage,
            'currentPage' => $page,
            'start' => min(($page*$perPage)-($perPage-1), $totalrecord),
            'end' => min(($perPage*$page), $totalrecord),
            'totalrecord' => $totalrecord,
            'pager' => $this->model->pager,
            'keyword' => $keyword,
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('administrator/master/master_list', $data);
        //endindex
    }

    //INDEX
    public function verifikasi()
    {
        return $this->index(0);
    }

    //READfunction
    public function read($id=NULL)
    {
        $id = $id==NULL?$this->request->getPostGet("resi"):base64_decode(urldecode($id));

        $this->PageData->header .= ' :: Detail';
        $this->PageData->title = "Master Detail";
        $this->PageData->subtitle = [
            'Master' => 'administrator/Master/index',
            'Detail' => 'administrator/Master/read/' . urlencode(base64_encode($id)),
        ];
        $this->PageData->url = "administrator/Master/read/" . urlencode(base64_encode($id));
        
        $dataFind = $this->model->getById($id);

        if($dataFind == FALSE || $id == NULL){
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
        $data = [
            'data' => $this->model->getById($id), //getById on data
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('administrator/master/master_read', $data);
    }

    //READfunction
    public function update($id = NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("resi") : base64_decode(urldecode($id));

        $this->PageData->header .= ' :: Ubah Harga';
        $this->PageData->title = "Ubah Harga";
        $this->PageData->subtitle = [
            'Pickup' => 'administrator/Master/index',
            'Ubah Harga' => 'administrator/Master/update/' . urlencode(base64_encode($id)),
        ];
        $this->PageData->url = "administrator/Master/update/" . urlencode(base64_encode($id));

        $dataFind = $this->model->getById($id);

        if ($dataFind == FALSE || $id == NULL) {
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
        $data = [
            'data' => $this->model->getById($id), //getById on data
            'action' => site_url($this->PageData->parent . '/updateAction'),
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('administrator/master/master_form', $data);
    }

    //ACTIONUPDATEfunction
    public function updateAction()
    {
        $id = $this->request->getPostGet('oldresi');
        $dataFind = $this->model->getById($id);

        if ($dataFind == FALSE || $id == NULL) {
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        };

        $data = [
            'harga' => $this->request->getPost('harga')
        ];

        $this->model->update($id, $data);
        session()->setFlashdata('ci_flash_message', 'Update item success !');
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        return redirect()->back();
    }

    //DELETE
    public function delete($id=NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("resi") : base64_decode(urldecode($id));
        $row = $this->model->getById($id);

        if ($row && $id != NULL) {
            if (isset($row->foto)) {
                if ($row->foto != NULL) {
                    safeUnlink($row->foto);
                    safeUnlink($row->thumbnail);
                }
            }
            
            $this->model->delete($id);
            $pickup = new Pickup_model();
            $pickup->update($row->id_pickup, ["status" => 0]);
            $d = new Deliver_model();
            $d->delete($row->resi);
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        } else {
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
    }

    //DELETE
    public function set_valid($id = NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("resi") : base64_decode(urldecode($id));
        $row = $this->model->getById($id);

        if ($row && $id != NULL) {

            $this->model->update($id, ["status" => 1]);
            return redirect()->back();
        } else {
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->back();
        }
    }

    //DELETEBATCH
    public function deleteBatch()
    {
        $arr = $this->request->getPost("removeme");
        $res = 0;
        if ($arr!=NULL) {
            if (count($arr)>=1) {
                $d = new Deliver_model();
                foreach ($arr as $key => $id) {
                    $row = $this->model->getById($id);
                    if (! $row || $id == NULL) continue;
                    if (isset($row->foto)) {
                        if ($row->foto != NULL) {
                            safeUnlink($row->foto);
                            safeUnlink($row->thumbnail);
                        }
                    }
                    $this->model->delete($id);
                    $d->delete($row->resi);
                    $res++;
                }
            }
        }

        session()->setFlashdata('ci_flash_message', "$res data deleted !");
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    //TRUNCATE
    public function truncate()
    {
        $this->model->truncate();
        session()->setFlashdata('ci_flash_message', 'Data truncated !');
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    // FORMVALIDATION
    private function isRequestValid(){
        $res = FALSE;

        $this->validation->setRules([
                'resi' => 'trim|required|max_length[50]',
                'id_olshop' => 'trim|required|max_length[25]',
                'harga' => 'trim|required|min_length[1]|max_length[11]',
                'status' => 'trim|required|max_length[11]',
        ]);

        if ($this->validation->withRequest($this->request)->run() == TRUE) {
            $res = TRUE;
        }else{
            $errors = $this->validation->getErrors();
            foreach ($errors as $key => $value) {
                session()->setFlashdata('ci_flash_message_'.$key, $value);
                session()->setFlashdata('ci_flash_message_'.$key.'_type', 'is-invalid');
            }
        }
        return $res;
    }

    //PRINTfunction
    public function printAll(){
        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL){
            if (session()->has("sorting_table")) {
                if (session("sorting_table")==$this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        }else{
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if(in_array($sortcolumn, $this->model->getFields())){
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
            }
        }

        $this->PageData->title = "Master Data";
        $this->PageData->subtitle = ["Master", "Print All"];
        $this->PageData->url = "administrator/Master/printAll/";

        $data = array(
            'Page' => $this->PageData,
            'data' => $this->model->sort()->findAll(),
            'start' => 0
        );
        
        return view('administrator/master/master_print', $data);
    }
    
    //ENDFUNCTION
}
