<?php
namespace App\Controllers\kurir;
/**
* Auto Generated By TrigerIgniter v1
* Codeigniter Version 4.1.x
* Codeigniter Controller
**/

use App\Models\Deliver_model;
use App\Controllers\BaseController;
use App\Models\Kurir_model;
use App\Models\Master_model;

class Deliver extends BaseController
{
    protected $model; //Default Models Of this Controler

    /**
     * Class constructor.
     */ 
    public function __construct()
    {
        $this->model = new Deliver_model(); //Set Default Models Of this Controller
        $this->Template = $this->defaultTemplate(); //Template Of this Page
        $this->pager = \Config\Services::pager(); // Pagination
        $this->validation =  \Config\Services::validation();
    }

    // This event executed after constructor
    protected function onLoad(){
        $this->PageData->parent = "kurir/Deliver";
        $this->PageData->header = (session()->has("level") ? NULL : ucfirst(str_replace("_", '', session("level"))) . " :: ") . 'Deliver';
        $this->PageData->access = ["kurir"];
        // check access level
        if (! $this->access_allowed()) {
            session()->setFlashdata("ci_login_flash_message", 'Login session outdate. Please re-Login !');
            session()->setFlashdata("ci_login_flash_message_type", "text-danger");
            throw new \CodeIgniter\Router\Exceptions\RedirectException();
        };
    
    }

    //TEMPLATE OF THIS PAGE
    private function defaultTemplate()
    {
        return (object) [
            'container' => 'kurir/_templates/Container',
            'header' => 'kurir/_templates/header',
            'navbar' => 'kurir/_templates/navbar',
            'sidebar' => 'kurir/_templates/sidebar',
            'footer' => 'kurir/_templates/footer',
        ];
    }
    
    private function access_allowed(){
        $allowed = FALSE;
        if (count($this->PageData->access)==0) return TRUE;
        if (! session()->has("level"))  return FALSE;
        foreach ($this->PageData->access as $key => $value) {
            if(session("level")==$value){
                $allowed=TRUE;
                break;
            }
        };
        return $allowed;
    }

    //INDEX
    public function index($isDone = FALSE)
    {
        //indexstart
        
        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL){
            if (session()->has("sorting_table")) {
                if (session("sorting_table")==$this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        }else{
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            $sortorder = strtoupper($sortorder);
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if (in_array($sortcolumn, $this->model->getFields())){
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
                session()->set('sortcolumn', $sortcolumn);
                session()->set('sortorder', $sortorder);
                session()->set('sorting_table', $this->model->table);
            }else{
                $sortcolumn = NULL;
                $sortorder = NULL;
                session()->remove('sortcolumn');
                session()->remove('sortorder');
                session()->remove('sorting_table');
            }
        }

        // How many data shows each page
        $perPage = $this->request->getPostGet("perPage");
        if ($perPage == NULL) {
            if (session()->has("paging_table")) {
                if (session("paging_table")==$this->model->table) {
                    $perPage = session("perPage");
                };
            };
        };
        if ($perPage != NULL) {
            // Minimum data per-page = 2
            if ($perPage <= 0) $perPage = 2;
            session()->set('perPage', $perPage);
            session()->set('paging_table', $this->model->table);
        }else{
            // Default data per-page = 20
            $perPage = 20;
            session()->remove('paging_table');
            session()->remove('perPage');
        }

        $page = $this->request->getGet("page");
        $page = $page<=0?1:$page;
        $keyword = $this->request->getGetPost("keyword");      

        $this->PageData->title = "Delivery Barang";
        $this->PageData->subtitle = [
            $this->PageData->title => 'kurir/Deliver/index'
        ];
        $this->PageData->url = "kurir/Deliver/index";
        if ($isDone) {
            $this->model->where('username_kurir', session('username'))->where("deliver.status = 2", NULL, FALSE);
            $totalrecord = $this->model->getData($keyword)->countAllResults();
            $this->model->where('username_kurir', session('username'))->where("deliver.status = 2", NULL, FALSE);
        }else {
            $this->model->where('username_kurir', session('username'))->where("deliver.status < 2", NULL, FALSE);
            $totalrecord = $this->model->getData($keyword)->countAllResults();
            $this->model->where('username_kurir', session('username'))->where("deliver.status < 2", NULL, FALSE);
        }
        // $this->model->where('username_kurir', session('username'));
        // $totalrecord = $this->model->getData($keyword)->countAllResults();
        // $this->model->where('username_kurir', session('username'));

        $data = [
            'sortcolumn' => $sortcolumn,
            'sortorder' => $sortorder,
            'data' => $this->model->getData($keyword)->paginate($perPage),
            'perPage' => $perPage,
            'currentPage' => $page,
            'start' => min(($page*$perPage)-($perPage-1), $totalrecord),
            'end' => min(($perPage*$page), $totalrecord),
            'totalrecord' => $totalrecord,
            'pager' => $this->model->pager,
            'keyword' => $keyword,
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('kurir/deliver/deliver_list', $data);
        //endindex
    }

    public function history()
    {
        return $this->index(TRUE);
    }

    //READfunction
    public function read($id=NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("resi") : base64_decode(urldecode($id));

        $this->PageData->header .= ' :: Detail';
        $this->PageData->title = "Detail Barang";
        $this->PageData->subtitle = [
            'Master' => 'kurir/Master/index',
            'Detail' => 'kurir/Master/read/' . urlencode(base64_encode($id)),
        ];
        $this->PageData->url = "kurir/Master/read/" . urlencode(base64_encode($id));
        $master = new Master_model();
        $dataFind = $master->getById($id);

        if ($dataFind == FALSE || $id == NULL) {
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
        $data = [
            'data' => $master->getById($id), //getById on data
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('kurir/master/master_read', $data);
    }

    //CREATEfunction
    public function create()
    {
        $this->PageData->header .= ' :: ' . 'Delivery Barang';
        $this->PageData->title = "Add Stock Delivery";
        $this->PageData->subtitle = [
            'Delivery' => 'kurir/Deliver/index',
            'Create New Item' => 'kurir/Deliver/create',
        ];
        $this->PageData->url = "kurir/Deliver/create";
        $master = new Master_model();
        $kurir = new Kurir_model();
        $data = [
            'data' => (object) [
                'id' => set_value('id', generateId("DLVR")),
                'resi' => set_value('resi'),
            ],
            'listResi' => $master->where("status", 1)->findAll(),
            'disableResi' => FALSE,
            'action' => site_url($this->PageData->parent . '/createAction'),
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('kurir/deliver/deliver_add', $data);
    }

    //ACTIONCREATEfunction
    public function createAction()
    {
        $data = [
            'id' => generateId("DLVR"),
            'resi' => $this->request->getPost('resi'),
            'username_kurir' => session("username"),
            'tanggal' => strtotime("now"),
            'status' => 0,
            'keterangan' => NULL,
        ];

        $this->model->insert($data);
        $m = new Master_model();
        $m->update($this->request->getPost('resi'), ['status' => 2]);
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    //UPDATEfunction
    public function update($id = NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("id") : base64_decode(urldecode($id));

        $this->PageData->header .= ' :: ' . 'Update Item';
        $this->PageData->title = "Process On Delivery";
        $this->PageData->subtitle = [
            'Delivery' => 'kurir/Deliver/index',
            'Update Delivery Item' => 'kurir/Deliver/update' . urlencode(base64_encode($id)),
        ];
        $this->PageData->url = "kurir/Deliver/update" . urlencode(base64_encode($id));

        $dataFind = $this->model->getById($id);

        if ($dataFind == FALSE || $id == NULL) {
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
        $master = new Master_model();
        $kurir = new Kurir_model();
        $data = [
            'data' => (object) [
                'id' => set_value('id', $dataFind->id),
                'resi' => set_value('resi', $dataFind->resi),
                'foto' => set_value('foto', $dataFind->foto),
                'username_kurir' => set_value('username_kurir', $dataFind->username_kurir),
                'status' => set_value('status', $dataFind->status),
                'keterangan' => set_value('keterangan', $dataFind->keterangan)
            ],
            'action' => site_url($this->PageData->parent . '/updateAction'),
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('kurir/deliver/deliver_form', $data);
    }

    //ACTIONUPDATEfunction
    public function updateAction()
    {
        $id = $this->request->getPostGet('oldid');
        $dataFind = $this->model->getById($id);

        if ($dataFind == FALSE || $id == NULL) {
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        };

        $data = [
            'status' => $this->request->getPost('status'),
            'keterangan' => $this->request->getPost('keterangan'),
        ];

        $this->model->update($id, $data);
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }
    
    //ENDFUNCTION
}
