<?php
namespace App\Controllers\kurir;
/**
* Auto Generated By TrigerIgniter v1
* Codeigniter Version 4.1.x
* Codeigniter Controller
**/

use App\Models\Pickup_model;
use App\Controllers\BaseController;
use App\Models\Master_model;
use App\Models\Olshop_model;

class Pickup extends BaseController
{
    protected $model; //Default Models Of this Controler

    /**
     * Class constructor.
     */ 
    public function __construct()
    {
        $this->model = new Pickup_model(); //Set Default Models Of this Controller
        $this->Template = $this->defaultTemplate(); //Template Of this Page
        $this->pager = \Config\Services::pager(); // Pagination
        $this->validation =  \Config\Services::validation();
    }

    // This event executed after constructor
    protected function onLoad(){
        $this->PageData->parent = "kurir/Pickup";
        $this->PageData->header = (session()->has("level") ? NULL : ucfirst(str_replace("_", '', session("level"))) . " :: ") . 'Pickup';
        $this->PageData->access = ["kurir"];
        // check access level
        if (! $this->access_allowed()) {
            session()->setFlashdata("ci_login_flash_message", 'Login session outdate. Please re-Login !');
            session()->setFlashdata("ci_login_flash_message_type", "text-danger");
            throw new \CodeIgniter\Router\Exceptions\RedirectException();
        };
    
    }

    //TEMPLATE OF THIS PAGE
    private function defaultTemplate()
    {
        return (object) [
            'container' => 'kurir/_templates/Container',
            'header' => 'kurir/_templates/header',
            'navbar' => 'kurir/_templates/navbar',
            'sidebar' => 'kurir/_templates/sidebar',
            'footer' => 'kurir/_templates/footer',
        ];
    }
    
    private function access_allowed(){
        $allowed = FALSE;
        if (count($this->PageData->access)==0) return TRUE;
        if (! session()->has("level"))  return FALSE;
        foreach ($this->PageData->access as $key => $value) {
            if(session("level")==$value){
                $allowed=TRUE;
                break;
            }
        };
        return $allowed;
    }

    //INDEX
    public function index()
    {
        //indexstart

        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL) {
            if (session()->has("sorting_table")) {
                if (session("sorting_table") == $this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        } else {
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            $sortorder = strtoupper($sortorder);
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if (in_array($sortcolumn, $this->model->getFields())) {
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
                session()->set('sortcolumn', $sortcolumn);
                session()->set('sortorder', $sortorder);
                session()->set('sorting_table', $this->model->table);
            } else {
                $sortcolumn = NULL;
                $sortorder = NULL;
                session()->remove('sortcolumn');
                session()->remove('sortorder');
                session()->remove('sorting_table');
            }
        }

        // How many data shows each page
        $perPage = $this->request->getPostGet("perPage");
        if ($perPage == NULL) {
            if (session()->has("paging_table")) {
                if (session("paging_table") == $this->model->table) {
                    $perPage = session("perPage");
                };
            };
        };
        if ($perPage != NULL) {
            // Minimum data per-page = 2
            if ($perPage <= 0) $perPage = 2;
            session()->set('perPage', $perPage);
            session()->set('paging_table', $this->model->table);
        } else {
            // Default data per-page = 20
            $perPage = 20;
            session()->remove('paging_table');
            session()->remove('perPage');
        }

        $page = $this->request->getGet("page");
        $page = $page <= 0 ? 1 : $page;
        $keyword = $this->request->getGetPost("keyword");
        $this->model->where(["kurir" => session("username"), 'status' => 0]);
        $totalrecord = $this->model->getData($keyword)->countAllResults();

        $this->PageData->title = "Pickup";
        $this->PageData->subtitle = [
            $this->PageData->title => 'kurir/Pickup/index'
        ];
        $this->PageData->url = "kurir/Pickup/index";
        $this->model->where(["kurir" => session("username"), 'status' => 0]);
        $data = [
            'sortcolumn' => $sortcolumn,
            'sortorder' => $sortorder,
            'data' => $this->model->getData($keyword)->paginate($perPage),
            'perPage' => $perPage,
            'currentPage' => $page,
            'start' => min(($page * $perPage) - ($perPage - 1), $totalrecord),
            'end' => min(($perPage * $page), $totalrecord),
            'totalrecord' => $totalrecord,
            'pager' => $this->model->pager,
            'keyword' => $keyword,
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('kurir/pickup/pickup_list', $data);
        //endindex
    }

    //UPDATEfunction
    public function update($id=NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("id") : base64_decode(urldecode($id));

        $this->PageData->header .= ' :: ' . 'Update Item';

        $dataFind = $this->model->getById($id);

        if($dataFind == FALSE || $id == NULL){
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
        $this->PageData->title = "Pickup " . $dataFind->nama_olshop;
        $this->PageData->subtitle = [
            'Pickup' => 'kurir/Pickup/index',
            'Update Item' => 'kurir/Pickup/update/' . urlencode(base64_encode($id)),
        ];
        $this->PageData->url = "kurir/Pickup/update/" . urlencode(base64_encode($id));
        $ols = new Olshop_model();
        $master = new Master_model();
        $data = [
            'data' => (object) [
                'id' => set_value('id', $dataFind->id),
                'id_olshop' => set_value('id_olshop', $dataFind->id_olshop),
                'jumlah_barang' => set_value('jumlah_barang', $dataFind->jumlah_barang),
                'kurir' => set_value('kurir', $dataFind->kurir),
            ],
            'olshop' => $ols->getById($dataFind->id_olshop),
            'master' => $master->getBy("id_pickup", $dataFind->id),
            'action' => site_url($this->PageData->parent.'/updateAction'),
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('kurir/pickup/pickup_form', $data);
    }
    
    //ACTIONUPDATEfunction
    public function updateAction()
    {
        $id = $this->request->getPostGet('oldid');
        $dataFind = $this->model->getById($id);

        if($dataFind == FALSE || $id == NULL){
            session()->setFlashdata('ci_flash_message', 'Sorry... This data is missing !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        };

        if($this->isRequestValid() == FALSE){
            return $this->update(urlencode(base64_encode($id)));
        };

        $data = [
            'resi' => generateId("R"),
            'id_pickup' => $this->request->getPost('oldid'),
            'id_olshop' => $this->request->getPost('id_olshop'),
            'harga' => $this->request->getPost('harga'),
            'kurir' => session("username"),
            'status' => 0,
        ];

        if ($foto = $this->request->getFile('foto')) {
            if ($foto->isValid()) {
                if (!$foto->hasMoved()) {
                    $foto->move('uploads/master/', $foto->getRandomName());
                }
                $data['foto'] = 'uploads/master/' . $foto->getName();
            } else {
                session()->setFlashdata('ci_flash_message_foto', $foto->getErrorString() . ' (' . $foto->getError() . ')');
                session()->setFlashdata('ci_flash_message_foto_type', ' text-danger ');
            };
        };
        $master = new Master_model();
        $master->insert($data);
        return $this->update(urlencode(base64_encode($id)));
        session()->setFlashdata('ci_flash_message', 'Pickup Barang Tersimpan !');
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        // return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    //DELETE
    public function remove($id = NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("resi") : base64_decode(urldecode($id));
        $master = new Master_model();
        $row = $master->getById($id);

        if ($id != NULL) {
            $d = $row->id_pickup;
            if (isset($row->foto)) {
                if ($row->foto != NULL) {
                    safeUnlink($row->foto);
                }
            }

            $master->delete($id);
            session()->setFlashdata('ci_flash_message', 'Delete item success !');
            session()->setFlashdata('ci_flash_message_type', ' alert-success ');
            return $this->update(urlencode(base64_encode($d)));
        } else {
            session()->setFlashdata('ci_flash_message', 'Delete item failed !');
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->back();
        }
    }

    public function done($id)
    {
        $id = base64_decode(urldecode($id));
        $master = new Master_model();
        $c = $master->select("COUNT(resi) AS c")->where('id_pickup', $id)->first()->c;
        $dataFind = $this->model->getById($id);
        if ($dataFind->jumlah_barang <= $c){
            $this->model->update($id, ['status' => 1]);
        }
        return redirect()->back();
    }

    // FORMVALIDATION
    private function isRequestValid(){
        $res = FALSE;

        $this->validation->setRules([
            'harga' => 'trim|required|min_length[1]|max_length[15]',
        ]);

        if ($this->validation->withRequest($this->request)->run() == TRUE) {
            $res = TRUE;
        }else{
            $errors = $this->validation->getErrors();
            foreach ($errors as $key => $value) {
                session()->setFlashdata('ci_flash_message_'.$key, $value);
                session()->setFlashdata('ci_flash_message_'.$key.'_type', 'is-invalid');
            }
        }
        return $res;
    }

    //ENDFUNCTION
}
